/**
 * Maps API-Football English team names → { de: German name, flag: emoji }
 * Covers all 48 WM 2026 qualifiers + common alternates.
 */
export const TEAM_MAP = {
  // Hosts
  "United States":        { de: "USA",                        flag: "🇺🇸" },
  "USA":                  { de: "USA",                        flag: "🇺🇸" },
  "Canada":               { de: "Kanada",                     flag: "🇨🇦" },
  "Mexico":               { de: "Mexiko",                     flag: "🇲🇽" },

  // UEFA
  "Germany":              { de: "Deutschland",                flag: "🇩🇪" },
  "France":               { de: "Frankreich",                 flag: "🇫🇷" },
  "Spain":                { de: "Spanien",                    flag: "🇪🇸" },
  "England":              { de: "England",                    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  "Portugal":             { de: "Portugal",                   flag: "🇵🇹" },
  "Netherlands":          { de: "Niederlande",                flag: "🇳🇱" },
  "Italy":                { de: "Italien",                    flag: "🇮🇹" },
  "Belgium":              { de: "Belgien",                    flag: "🇧🇪" },
  "Croatia":              { de: "Kroatien",                   flag: "🇭🇷" },
  "Switzerland":          { de: "Schweiz",                    flag: "🇨🇭" },
  "Denmark":              { de: "Dänemark",                   flag: "🇩🇰" },
  "Austria":              { de: "Österreich",                 flag: "🇦🇹" },
  "Poland":               { de: "Polen",                      flag: "🇵🇱" },
  "Serbia":               { de: "Serbien",                    flag: "🇷🇸" },
  "Scotland":             { de: "Schottland",                 flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  "Hungary":              { de: "Ungarn",                     flag: "🇭🇺" },
  "Turkey":               { de: "Türkei",                     flag: "🇹🇷" },
  "Ukraine":              { de: "Ukraine",                    flag: "🇺🇦" },
  "Czech Republic":       { de: "Tschechien",                 flag: "🇨🇿" },
  "Czechia":              { de: "Tschechien",                 flag: "🇨🇿" },
  "Slovakia":             { de: "Slowakei",                   flag: "🇸🇰" },
  "Norway":               { de: "Norwegen",                   flag: "🇳🇴" },
  "Sweden":               { de: "Schweden",                   flag: "🇸🇪" },
  "Greece":               { de: "Griechenland",               flag: "🇬🇷" },
  "Romania":              { de: "Rumänien",                   flag: "🇷🇴" },
  "Wales":                { de: "Wales",                      flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  "Albania":              { de: "Albanien",                   flag: "🇦🇱" },
  "Slovenia":             { de: "Slowenien",                  flag: "🇸🇮" },
  "Finland":              { de: "Finnland",                   flag: "🇫🇮" },
  "Iceland":              { de: "Island",                     flag: "🇮🇸" },
  "Bosnia and Herzegovina": { de: "Bosnien-Herzegowina",      flag: "🇧🇦" },
  "Bosnia & Herzegovina":   { de: "Bosnien-Herzegowina",      flag: "🇧🇦" },
  "North Macedonia":      { de: "Nordmazedonien",             flag: "🇲🇰" },
  "Bulgaria":             { de: "Bulgarien",                  flag: "🇧🇬" },
  "Montenegro":           { de: "Montenegro",                 flag: "🇲🇪" },
  "Georgia":              { de: "Georgien",                   flag: "🇬🇪" },

  // CONMEBOL
  "Brazil":               { de: "Brasilien",                  flag: "🇧🇷" },
  "Argentina":            { de: "Argentinien",                flag: "🇦🇷" },
  "Uruguay":              { de: "Uruguay",                    flag: "🇺🇾" },
  "Colombia":             { de: "Kolumbien",                  flag: "🇨🇴" },
  "Ecuador":              { de: "Ecuador",                    flag: "🇪🇨" },
  "Chile":                { de: "Chile",                      flag: "🇨🇱" },
  "Paraguay":             { de: "Paraguay",                   flag: "🇵🇾" },
  "Venezuela":            { de: "Venezuela",                  flag: "🇻🇪" },
  "Bolivia":              { de: "Bolivien",                   flag: "🇧🇴" },
  "Peru":                 { de: "Peru",                       flag: "🇵🇪" },

  // CONCACAF
  "Jamaica":              { de: "Jamaika",                    flag: "🇯🇲" },
  "Costa Rica":           { de: "Costa Rica",                 flag: "🇨🇷" },
  "Honduras":             { de: "Honduras",                   flag: "🇭🇳" },
  "Panama":               { de: "Panama",                     flag: "🇵🇦" },
  "El Salvador":          { de: "El Salvador",                flag: "🇸🇻" },
  "Trinidad and Tobago":  { de: "Trinidad und Tobago",        flag: "🇹🇹" },
  "Cuba":                 { de: "Kuba",                       flag: "🇨🇺" },
  "Haiti":                { de: "Haiti",                      flag: "🇭🇹" },
  "Guatemala":            { de: "Guatemala",                  flag: "🇬🇹" },
  "Curacao":              { de: "Curaçao",                    flag: "🇨🇼" },
  "Curaçao":              { de: "Curaçao",                    flag: "🇨🇼" },

  // CAF
  "Senegal":              { de: "Senegal",                    flag: "🇸🇳" },
  "Morocco":              { de: "Marokko",                    flag: "🇲🇦" },
  "Cameroon":             { de: "Kamerun",                    flag: "🇨🇲" },
  "Nigeria":              { de: "Nigeria",                    flag: "🇳🇬" },
  "Ghana":                { de: "Ghana",                      flag: "🇬🇭" },
  "Egypt":                { de: "Ägypten",                    flag: "🇪🇬" },
  "Ivory Coast":          { de: "Elfenbeinküste",             flag: "🇨🇮" },
  "Cote d'Ivoire":        { de: "Elfenbeinküste",             flag: "🇨🇮" },
  "Tunisia":              { de: "Tunesien",                   flag: "🇹🇳" },
  "Algeria":              { de: "Algerien",                   flag: "🇩🇿" },
  "Mali":                 { de: "Mali",                       flag: "🇲🇱" },
  "South Africa":         { de: "Südafrika",                  flag: "🇿🇦" },
  "DR Congo":             { de: "DR Kongo",                   flag: "🇨🇩" },
  "Congo DR":             { de: "DR Kongo",                   flag: "🇨🇩" },
  "Zambia":               { de: "Sambia",                     flag: "🇿🇲" },
  "Guinea":               { de: "Guinea",                     flag: "🇬🇳" },
  "Cape Verde":           { de: "Kap Verde",                  flag: "🇨🇻" },
  "Tanzania":             { de: "Tansania",                   flag: "🇹🇿" },
  "Uganda":               { de: "Uganda",                     flag: "🇺🇬" },
  "Gabon":                { de: "Gabun",                      flag: "🇬🇦" },
  "Mozambique":           { de: "Mosambik",                   flag: "🇲🇿" },
  "Comoros":              { de: "Komoren",                    flag: "🇰🇲" },

  // AFC
  "Japan":                { de: "Japan",                      flag: "🇯🇵" },
  "South Korea":          { de: "Südkorea",                   flag: "🇰🇷" },
  "Korea Republic":       { de: "Südkorea",                   flag: "🇰🇷" },
  "Saudi Arabia":         { de: "Saudi-Arabien",              flag: "🇸🇦" },
  "Iran":                 { de: "Iran",                       flag: "🇮🇷" },
  "Australia":            { de: "Australien",                 flag: "🇦🇺" },
  "Iraq":                 { de: "Irak",                       flag: "🇮🇶" },
  "Jordan":               { de: "Jordanien",                  flag: "🇯🇴" },
  "Uzbekistan":           { de: "Usbekistan",                 flag: "🇺🇿" },
  "Oman":                 { de: "Oman",                       flag: "🇴🇲" },
  "Bahrain":              { de: "Bahrain",                    flag: "🇧🇭" },
  "Kuwait":               { de: "Kuwait",                     flag: "🇰🇼" },
  "United Arab Emirates": { de: "Vereinigte Arabische Emirate", flag: "🇦🇪" },
  "Qatar":                { de: "Katar",                      flag: "🇶🇦" },
  "China":                { de: "China",                      flag: "🇨🇳" },
  "China PR":             { de: "China",                      flag: "🇨🇳" },
  "Indonesia":            { de: "Indonesien",                 flag: "🇮🇩" },
  "Palestine":            { de: "Palästina",                  flag: "🇵🇸" },
  "India":                { de: "Indien",                     flag: "🇮🇳" },
  "Thailand":             { de: "Thailand",                   flag: "🇹🇭" },
  "Vietnam":              { de: "Vietnam",                    flag: "🇻🇳" },
  "Kyrgyzstan":           { de: "Kirgisistan",                flag: "🇰🇬" },
  "Tajikistan":           { de: "Tadschikistan",              flag: "🇹🇯" },

  // OFC
  "New Zealand":          { de: "Neuseeland",                 flag: "🇳🇿" },
  "Papua New Guinea":     { de: "Papua-Neuguinea",            flag: "🇵🇬" },
  "Vanuatu":              { de: "Vanuatu",                    flag: "🇻🇺" },
  "Solomon Islands":      { de: "Salomonen",                  flag: "🇸🇧" },
};

export function mapTeam(englishName) {
  const entry = TEAM_MAP[englishName];
  return {
    name: entry?.de ?? englishName,
    flag: entry?.flag ?? "",
  };
}
